export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL'
export const STUDENT_DETAILS_RESET = 'STUDENT_DETAILS_RESET'

export const UPDATE_STUDENT_DETAILS_REQUEST = 'UPDATE_STUDENT_DETAILS_REQUEST'
export const UPDATE_STUDENT_DETAILS_SUCCESS = 'UPDATE_STUDENT_DETAILS_SUCCESS'
export const UPDATE_STUDENT_DETAILS_FAIL = 'UPDATE_STUDENT_DETAILS_FAIL'





